# Generated by Django 3.2 on 2021-12-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_m3u8',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
