# Generated by Django 3.2 on 2021-11-21 17:22

from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=storage.models.file_path.path_name),
        ),
    ]
