# Generated by Django 3.2 on 2022-01-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_files_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='public',
            field=models.BooleanField(blank=True, default=False, help_text='すべてのユーザーに公開する。', null=True),
        ),
    ]
