# Generated by Django 3.2 on 2022-01-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_files_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='public',
            field=models.BooleanField(default=False, help_text='すべてのユーザーに公開する。'),
        ),
    ]
