# Generated by Django 3.2 on 2021-11-13 16:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image_origin',
            field=models.ImageField(blank=True, default='static/default_image/defa.png', null=True, upload_to=accounts.models.ImageChnge.get_image_path, verbose_name='ユーザーアイコン'),
        ),
    ]
